[package]
name = "rust_blogpost_ui"
version = "0.1.0"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]

[dependencies]
cursive = "0.4"
lazy_static = "0.2"

reqwest = "0.4"
scraper = "0.4"

serde = "0.9"
serde_derive = "0.9"
